"""
lantern

Public package surface for the Lantern Babel Codex Bridge.

Re-exports the stable, frozen classes/functions from the core,
agent, and protocol modules so callers can do:

    from lantern import Lantern, LanternAgent, create_observation_share

instead of reaching into submodules directly. Submodules remain
importable individually (lantern.core, lantern.agent, lantern.protocol)
for callers who want to be explicit about which layer they depend on.
"""

from .core import (
    Chronicle,
    Contradiction,
    Evidence,
    EvidenceKernel,
    EventBus,
    KernelEvent,
    Lantern,
    Observation,
    ResolutionEvent,
)
from .agent import LanternAgent
from .compatibility import (
    CompatibilityResult,
    can_exchange,
    negotiate,
)
from .continuity import (
    AHEAD,
    BEHIND,
    COMPATIBLE,
    CONTINUITY_STATES,
    ContinuityResult,
    DIVERGED,
    INCOMPATIBLE,
    Watermark,
    compare_watermarks,
    local_watermark,
    parse_remote_watermark,
)
from .handshake import (
    HandshakeRequest,
    HandshakeResponse,
    create_handshake,
    evaluate_handshake,
    handshake_summary,
)
from .heartbeat import (
    ConnectionState,
    Heartbeat,
    UNREACHABLE,
    create_heartbeat,
    evaluate_connection,
)
from .participants import (
    COMPATIBILITY_STATES,
    COMPATIBLE as PARTICIPANT_COMPATIBLE,
    INCOMPATIBLE as PARTICIPANT_INCOMPATIBLE,
    REQUIRES_NEGOTIATION,
    UNKNOWN as PARTICIPANT_UNKNOWN,
    ParticipantView,
    find as find_participant,
    inspect as inspect_participant,
    inspect_all as inspect_all_participants,
    next_verification_step,
)
from .protocol import (
    PROTOCOL_VERSION,
    ProtocolMessage,
    create_codex_update,
    create_evidence_request,
    create_message,
    create_observation_share,
    validate_message,
)
from .rendezvous import (
    AWAITING_HANDSHAKE,
    EXPIRED,
    JoinMonitor,
    JoinRequest,
)
from .router import LanternRouter, RouteResult
from .boundary import LanternBoundary
from .architecture import (
    ArchitectureRegistry,
    REGISTRY,
    architecture_status,
)
from .orchestration import (
    CORE_WORKERS,
    DELEGATION_STATUSES,
    NEVER_EXTERNALLY_EXPOSE,
    ORCHESTRATION_VERSION,
    PROTECTED_AUTHORITIES,
    PROVENANCE_CLASSES,
    REMOTE_PROVENANCE_CLASSES,
    SELF_CHANGE_STATUSES,
    SPECIALIZED_WORKERS,
    TERMINAL_DELEGATION_STATUSES,
    CapabilityDescriptor,
    CapabilityRegistry,
    DelegationRecord,
    OrchestrationPlanner,
    PlanStep,
    ProvenanceTag,
    SelfChangeProposal,
    VerificationPolicy,
    create_default_registry,
)
from .contact_ledger import (
    CONTACT_LEDGER_VERSION,
    CONTACT_STATES,
    CONTACT_TYPES,
    EVIDENCE_BACKED_STATES,
    FIRST_CONTACT_MESSAGE,
    LEGACY_FIELD_LADDER,
    ContactAttempt,
    ContactEvidence,
    ContactLedger,
    build_contact_report,
)
from .compass import (
    COMPASS_VERSION,
    AllowedAction,
    AttentionItem,
    CompassReading,
    orient,
    what_is_allowed,
)
from .compression import (
    COMPRESSION_VERSION,
    CompressedCycle,
    CompressionViolation,
    compress_cycle,
)
from .mcp_client import (
    MCPClientUnavailable,
    MCPRemoteError,
    StdioMCPClient,
    StdioServerTarget,
)
from .mcp_integration import (
    MCP_INTEGRATION_VERSION,
    MCP_PROVENANCE_CLASS,
    MCPCapabilityBinding,
    MCPDiscoverySnapshot,
    MCPExecutionRequest,
    MCPExecutionResult,
    MCPIntegrationBoundary,
    MCPResourceDescriptor,
    MCPServerDiscovery,
    MCPToolDescriptor,
    MCPUnavailable,
    infer_bindings,
)
from .bridge import LanternAgentBridge, BridgeResult
from .codex_compare import ConceptComparison, ComparisonResult, compare_beliefs, comparison_summary
from .codex_explanation import Explanation, explain_comparison, explain_comparisons
from .evaluation import EvaluationResult, EvidenceCandidate, EvidenceEvaluationGate
from .federation import (
    FederationAdapter,
    FederationMetadata,
    FederationResult,
    RemoteObservation,
)
from .scars import (
    ACTIVE as SCAR_PERSISTENCE_ACTIVE,
    NOT_IMPLEMENTED as SCAR_PERSISTENCE_NOT_IMPLEMENTED,
    NETWORK_SCAR_OUTCOMES,
    SCAR_EVENT_TYPE,
    Scar,
    ScarPersistenceStatus,
    ScarRecord,
    create_network_scar,
    create_scar,
    describe_scar_claim,
    load_scar,
    persisted_record,
    record_from_replay,
    replay_scars,
    scar_persistence_status,
    should_record_network_scar,
    verify_scar_record,
)

__all__ = [
    "AHEAD",
    "AllowedAction",
    "ArchitectureRegistry",
    "AttentionItem",
    "MCPCapabilityBinding",
    "MCPClientUnavailable",
    "MCPDiscoverySnapshot",
    "MCPExecutionRequest",
    "MCPExecutionResult",
    "MCPIntegrationBoundary",
    "MCPRemoteError",
    "MCPResourceDescriptor",
    "MCPServerDiscovery",
    "MCPToolDescriptor",
    "MCPUnavailable",
    "MCP_INTEGRATION_VERSION",
    "MCP_PROVENANCE_CLASS",
    "StdioMCPClient",
    "StdioServerTarget",
    "infer_bindings",
    "REGISTRY",
    "architecture_status",
    "AWAITING_HANDSHAKE",
    "BEHIND",
    "BridgeResult",
    "CompassReading",
    "COMPASS_VERSION",
    "CompressedCycle",
    "CompressionViolation",
    "COMPRESSION_VERSION",
    "compress_cycle",
    "orient",
    "what_is_allowed",
    "COMPATIBILITY_STATES",
    "COMPATIBLE",
    "CONTINUITY_STATES",
    "Chronicle",
    "CompatibilityResult",
    "ComparisonResult",
    "ConceptComparison",
    "ConnectionState",
    "Contradiction",
    "ContinuityResult",
    "DIVERGED",
    "EXPIRED",
    "EvaluationResult",
    "Evidence",
    "EvidenceCandidate",
    "EvidenceEvaluationGate",
    "EvidenceKernel",
    "EventBus",
    "Explanation",
    "FederationAdapter",
    "FederationMetadata",
    "FederationResult",
    "HandshakeRequest",
    "HandshakeResponse",
    "Heartbeat",
    "INCOMPATIBLE",
    "JoinMonitor",
    "JoinRequest",
    "KernelEvent",
    "Lantern",
    "LanternAgent",
    "LanternAgentBridge",
    "LanternBoundary",
    "LanternRouter",
    "NETWORK_SCAR_OUTCOMES",
    "NEVER_EXTERNALLY_EXPOSE",
    "Observation",
    "ORCHESTRATION_VERSION",
    "PARTICIPANT_COMPATIBLE",
    "PARTICIPANT_INCOMPATIBLE",
    "PARTICIPANT_UNKNOWN",
    "ParticipantView",
    "PROTOCOL_VERSION",
    "PROTECTED_AUTHORITIES",
    "ProtocolMessage",
    "REQUIRES_NEGOTIATION",
    "RemoteObservation",
    "ResolutionEvent",
    "RouteResult",
    "SCAR_EVENT_TYPE",
    "SCAR_PERSISTENCE_ACTIVE",
    "SCAR_PERSISTENCE_NOT_IMPLEMENTED",
    "Scar",
    "ScarPersistenceStatus",
    "ScarRecord",
    "UNREACHABLE",
    "Watermark",
    "can_exchange",
    "compare_beliefs",
    "compare_watermarks",
    "comparison_summary",
    "create_codex_update",
    "create_evidence_request",
    "create_handshake",
    "create_heartbeat",
    "create_message",
    "create_network_scar",
    "create_observation_share",
    "create_default_registry",
    "create_outcome",
    "create_scar",
    "DELEGATION_STATUSES",
    "describe_scar_claim",
    "evaluate_connection",
    "evaluate_handshake",
    "explain_comparison",
    "explain_comparisons",
    "find_participant",
    "handshake_summary",
    "inspect_all_participants",
    "inspect_participant",
    "load_scar",
    "local_watermark",
    "negotiate",
    "next_verification_step",
    "parse_remote_watermark",
    "persisted_record",
    "record_from_replay",
    "replay_scars",
    "scar_persistence_status",
    "should_record_network_scar",
    "validate_message",
    "verify_scar_record",
    "CapabilityDescriptor",
    "CapabilityRegistry",
    "CONTACT_LEDGER_VERSION",
    "CONTACT_STATES",
    "CONTACT_TYPES",
    "ContactAttempt",
    "ContactEvidence",
    "ContactLedger",
    "build_contact_report",
    "CORE_WORKERS",
    "DelegationRecord",
    "EVIDENCE_BACKED_STATES",
    "FIRST_CONTACT_MESSAGE",
    "LEGACY_FIELD_LADDER",
    "OrchestrationPlanner",
    "PlanStep",
    "ProvenanceTag",
    "PROVENANCE_CLASSES",
    "REMOTE_PROVENANCE_CLASSES",
    "SelfChangeProposal",
    "SELF_CHANGE_STATUSES",
    "SPECIALIZED_WORKERS",
    "TERMINAL_DELEGATION_STATUSES",
    "VerificationPolicy",
]

__version__ = "0.84"
